[pytest]
pythonpath = .
markers =
    map: tests related to map logic
    ghost: tests related to ghost logic
    energizer: tests related to energizer logic
    animation: tests related to animation math
    pacman: tests related to pacman logic